export default {
  editor: {
    label: {
      en: 'Bar Chart',
    },
    icon: 'bar-chart-2',
  },
  properties: {
    title: {
      label: { en: 'Title' },
      type: 'Text',
      section: 'settings',
      bindable: true,
      defaultValue: 'Monthly Workflows',
    },
    data: {
      label: { en: 'Data' },
      type: 'Array',
      section: 'settings',
      bindable: true,
      defaultValue: [
        { "label": "Jan", "value": 65 },
        { "label": "Feb", "value": 59 },
        { "label": "Mar", "value": 80 },
        { "label": "Apr", "value": 81 },
        { "label": "May", "value": 56 },
        { "label": "Jun", "value": 55 }
      ],
      options: {
        expandable: true,
        getItemLabel: (item, index) => item.label || `Item ${index + 1}`,
        item: {
          type: 'Object',
          defaultValue: { label: 'Label', value: 50 },
        },
      },
    },
    labelField: {
        label: { en: 'Label Field' },
        type: 'ObjectPropertyPath',
        options: content => ({ object: content.data?.[0] || {} }),
        defaultValue: 'label',
    },
    valueField: {
        label: { en: 'Value Field' },
        type: 'ObjectPropertyPath',
        options: content => ({ object: content.data?.[0] || {} }),
        defaultValue: 'value',
    },
    showGrid: {
        label: { en: 'Show Y-axis Grid' },
        type: 'OnOff',
        section: 'settings',
        defaultValue: true,
    },
    showTooltip: {
        label: { en: 'Show Tooltip' },
        type: 'OnOff',
        section: 'settings',
        defaultValue: true,
    },
    backgroundColor: {
      label: { en: 'Background Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#1e293b',
    },
    titleColor: {
      label: { en: 'Title Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#f1f5f9',
    },
    barColor: {
      label: { en: 'Bar Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#3b82f6',
    },
    barHoverColor: {
      label: { en: 'Bar Hover Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#60a5fa',
    },
    barRadius: {
        label: { en: 'Bar Corner Radius'},
        type: 'Number',
        section: 'style',
        defaultValue: 4,
    },
    gridColor: {
      label: { en: 'Grid Line Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#334155',
    },
    axisLabelColor: {
      label: { en: 'Axis Label Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#94a3b8',
    },
    tooltipBackgroundColor: {
      label: { en: 'Tooltip BG Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#0f172a',
    },
    tooltipTextColor: {
      label: { en: 'Tooltip Text Color' },
      type: 'Color',
      section: 'style',
      bindable: true,
      defaultValue: '#f1f5f9',
    },
  },
};