export default {
  editor: {
    label: {
      en: 'Project Budget Chart',
    },
    icon: 'chart-pie',
  },
  properties: {
    data: {
      label: { en: 'Data (Raw Values)' },
      type: 'Array',
      section: 'settings',
      bindable: true,
      defaultValue: [
        { name: 'Development', value: 3437.1, color: '#3b82f6' },
        { name: 'Design', value: 1909.5, color: '#8b5cf6' },
        { name: 'Marketing', value: 1527.6, color: '#14b8a6' },
        { name: 'Hosting', value: 763.8, color: '#f97316' },
      ],
      options: {
        expandable: true,
        getItemLabel: (item, index) => item.name || `Slice ${index + 1}`,
        item: {
          type: 'Object',
          defaultValue: { name: 'New Slice', value: 1000, color: '#cccccc' },
          options: {
            item: {
              name: { label: 'Name', type: 'Text' },
              value: { label: 'Value', type: 'Number' },
              color: { label: 'Color', type: 'Color' },
            },
          },
        },
      },
    },
    valueField: {
      label: { en: 'Value Field' },
      type: 'ObjectPropertyPath',
      bindable: true,
      options: content => ({ object: content.data?.[0] || {} }),
      defaultValue: 'value',
    },
    nameField: {
        label: { en: 'Name Field' },
        type: 'ObjectPropertyPath',
        bindable: true,
        options: content => ({ object: content.data?.[0] || {} }),
        defaultValue: 'name',
    },
    colorField: {
      label: { en: 'Color Field' },
      type: 'ObjectPropertyPath',
      bindable: true,
      options: content => ({ object: content.data?.[0] || {} }),
      defaultValue: 'color',
    },
    title: {
        label: { en: 'Title' },
        type: 'Text',
        section: 'settings',
        bindable: true,
        defaultValue: 'Project Budget',
    },
    valuePrefix: {
        label: { en: 'Value Prefix' },
        type: 'Text',
        section: 'settings',
        bindable: true,
        defaultValue: '$',
    },
    centerSubText: {
        label: { en: 'Center Sub-text' },
        type: 'Text',
        section: 'settings',
        bindable: true,
        defaultValue: 'Total Spent',
    },
    backgroundColor: {
        label: { en: 'Background Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#1e293b',
    },
    titleColor: {
        label: { en: 'Title Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#e2e8f0',
    },
    centerValueColor: {
        label: { en: 'Center Value Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#f1f5f9',
    },
    centerSubtextColor: {
        label: { en: 'Center Sub-text Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#94a3b8',
    },
    legendTextColor: {
        label: { en: 'Legend Text Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#cbd5e0',
    },
    legendValueColor: {
        label: { en: 'Legend Value Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#e2e8f0',
    },
    dropdownTextColor: {
        label: { en: 'Dropdown Text Color' },
        type: 'Color',
        section: 'style',
        bindable: true,
        defaultValue: '#94a3b8',
    },
    strokeWidth: {
      label: { en: 'Donut Thickness' },
      type: 'Number',
      section: 'style',
      bindable: true,
defaultValue: 12,
    },
    titleSize: {
        label: { en: 'Title Font Size' },
        type: 'Length',
        section: 'style',
        bindable: true,
        defaultValue: '1.125rem',
    },
    centerValueSize: {
        label: { en: 'Center Value Font Size' },
        type: 'Length',
        section: 'style',
        bindable: true,
        defaultValue: '1.875rem',
    },
    centerSubTextSize: {
        label: { en: 'Center Sub-text Size' },
        type: 'Length',
        section: 'style',
        bindable: true,
        defaultValue: '0.875rem',
    },
    legendFontSize: {
        label: { en: 'Legend Font Size' },
        type: 'Length',
        section: 'style',
        bindable: true,
        defaultValue: '0.875rem',
    },
  },
};